### PR TITLE
sisl::byte_array_impl should be movable.

### PR DESCRIPTION
**Pull request by szmyd**

### CODE REVIEW

**Comment by szmyd** [comment]
Not ready, plan on setting moved value tag to `sentinel` to skip free?

**Comment by hkadayam** [comment]
Just one comment, should we bump up the conanfile patch version?

**Comment by szmyd** [comment]
> Just one comment, should we bump up the conanfile patch version?

Ah; yes. Good point. :+1:

**Review by hkadayam — APPROVED** [review]
Looks good.

**Pull request merged**
